server:
  port: 8080
spring:
  application:
    name: "authcrediya"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true

adapters:
  r2dbc:
    host: localhost
    port: 5432
    database: authentication_db
    schema: public
    username: postgres
    password: Admin

cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

entries:
  reactive-web:
    user: /api/v1/users
    solicited: /api/v1/users/verifyid
    auth:  /api/v1/login

business-configuration:
  minBaseSalary: 15000000

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret: "my-super-secret-key-that-is-long-enough-1234567890"
  expiration: 86400000